services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  KimaiPlugin\LiePayrollBundle\:
    resource: '../../*'
    exclude:
      - '../../{Resources,Migrations,Tests,composer.json}'

  KimaiPlugin\LiePayrollBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  # Service Aliases
  KimaiPlugin\LiePayrollBundle\Service\PdfRenderer:
    alias: KimaiPlugin\LiePayrollBundle\Service\HtmlRenderer

  # Explicit Services
  KimaiPlugin\LiePayrollBundle\Service\PayrollService:
    autowire: true
    
  KimaiPlugin\LiePayrollBundle\Service\HtmlRenderer:
    autowire: true
    
  KimaiPlugin\LiePayrollBundle\Service\PayrollCalculator:
    autowire: true
    
  KimaiPlugin\LiePayrollBundle\Service\SettingsService:
    autowire: true
    
  KimaiPlugin\LiePayrollBundle\Repository\PayrollPeriodRepository:
    autowire: true
